refactor(chocolatine): Fix commands

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -19,19 +19,19 @@ jobs:
       - uses: actions/checkout@v3
       - run: check.sh $(pwd) $(pwd)
       - run: |
-          if [ ! -s "coding-style-reports.log" ]; then
-            echo ""
-          else
-            while read ERROR
-            do
-              FILE=$("echo "$ERROR" | cut -d : -f 1")
-              LINE=$("echo "$ERROR" | cut -d : -f 2")
-              TYPE=$("echo "$ERROR" | cut -d : -f 3")
-              ERR=$("echo "$ERROR" | cut -d : -f 4")
-              echo "::error file=$FILE,line=$LINE,title=$TYPE coding style error::$ERR" 
-            done < "coding-style-reports.log"
-            exit 1
-          fi
+            if [ ! -s "coding-style-reports.log" ]; then
+              echo ""
+            else
+              while IFS=$'\n'; read ERROR
+              do
+                FILE=$(echo "$ERROR" | cut -d : -f 1)
+                LINE=$(echo "$ERROR" | cut -d : -f 2)
+                TYPE=$(echo "$ERROR" | cut -d : -f 3)
+                ERR=$(echo "$ERROR" | cut -d : -f 4)
+                echo "::error file=$FILE,line=$LINE,title=$TYPE coding style error::$ERR" 
+              done < "coding-style-reports.log"
+              exit 1
+            fi
 
   check_program_compilation:
     runs-on: ubuntu-latest
